FROM node:22-alpine AS builder
WORKDIR /landing
COPY ./package.json ./package-lock.json ./
RUN npm install --force
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /landing/dist /usr/share/nginx/html
