name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: nenad2807
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (main branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: docker.io/nenad2807/momentum.landing:latest
          push: true

      - name: Build and push Docker image (tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: docker.io/nenad2807/momentum.landing:${{ github.ref_name }}
          push: true

      - name: Build Docker image (Pull Requests)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: docker.io/nenad2807/momentum.landing:pr-${{ github.number }}
          push: false
